### ISSUE TITLE
Auto size is now fixed on avalonia 0.10.15

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaCommunity/MessageBox.Avalonia#108]
Auto size with MaxWidth/Height is now fixed.
My PR #65 to hack sizes to get it right may not be required anymore, please check

https://github.com/AvaloniaCommunity/MessageBox.Avalonia/blob/112fb9e18ee8cf26d73ff5e9be47e587a84fbec0/src/MessageBox.Avalonia/Views/MsBoxStandardWindow.xaml.cs#L38

**Comment by CreateLab** [comment]
may u send new pr if it needed
