### ISSUE TITLE
how to set Chinese charset use this MessageBox

### ISSUE THREAD

**Issue by protofabcode** [AvaloniaCommunity/MessageBox.Avalonia#122]
I don't know how to set Chinese charset use this MessageBox,someone help me,thanks

**Comment by lshiren** [comment]
Me too. The title is correct, but the string in the box is many rectangles.

**Comment by CreateLab** [comment]
https://github.com/AvaloniaCommunity/MessageBox.Avalonia/blob/master/src/MessageBox.Avalonia.Example/MainWindow.xaml.cs#L58

**Comment by CreateLab** [comment]
Check an example

**Comment by lcorel** [comment]
FontFamily = "Microsoft YaHei,Simsun"

https://github.com/AvaloniaCommunity/MessageBox.Avalonia/issues/77

**Comment by lcorel** [comment]
> 

//遇到乱码的组件，就给FontFamily赋值，
//windows 上, 微软雅黑 Microsoft YaHei msyh。
//Mac上，苹方 苹方-简 PingFang
FontFamily = "Microsoft YaHei,Simsun,苹方-简,宋体-简" // 使用英文逗号分隔
