### ISSUE TITLE
ButtonResult enum has [Flags] attribute

### ISSUE THREAD

**Issue by moon6969** [AvaloniaCommunity/MessageBox.Avalonia#133]
ButtonResult enum has [Flags] attribute, leading to weirdness like `Abort 0x3 = Yes 0x1 | No 0x2`
Is it intentional?
https://github.com/AvaloniaCommunity/MessageBox.Avalonia/blob/04afe5d11a24339e4ada3813e26ca05d7b10a7af/src/MessageBox.Avalonia/Enums/ButtonResult.cs#L8-L17

**Comment by CreateLab** [comment]
@IhateTrains mb this question is more actual for u

**Comment by IhateTrains** [comment]
Can't help, sorry. The attribute was present before I converted to file-scoped namespace:
https://github.com/AvaloniaCommunity/MessageBox.Avalonia/commit/74ba3500aa1c6c469607a8d0839a6ff7f0efb8c2#diff-dcebb6aaf05d8947529fe601ac58187838a2ae758b954d97ea8a64188dd4c999
Don't know why it's needed.
