### ISSUE TITLE
Message box is completely empty

### ISSUE THREAD

**Issue by foxt** [AvaloniaCommunity/MessageBox.Avalonia#134]
<img width="779" alt="Screenshot 2023-04-20 at 09 03 52" src="https://user-images.githubusercontent.com/12257112/233303325-d6b13c4a-6e6b-4fc2-83f4-a9cdf98503e7.png">
Using MessageBox.Avalonia 2.1.0, with Avalonia 0.10.18, on macOS 13.3. Trying to show a messagebox window results in a completely empty window.

**Comment by CreateLab** [comment]
Please try actual avalonia version. has no ability to reproduce
