### ISSUE TITLE
Suggestion: offer a UserControl API

### ISSUE THREAD

**Issue by aldelaro5** [AvaloniaCommunity/MessageBox.Avalonia#135]
So I was trying to integrate wasm support to my app and I ended up using the js interop with a js lib to provide something equivalent to MessageBox.Avalonia.

However, I wanted to experiment what would happen if you used DialogHost.Avalonia comibined with MessageBox.Avalonia and I found out it was actually close to working. It worked if I did some tricks on desktop, but it will never work on browser due to the need to create a window which is not supported.

So my idea was what if this offered a UserControl api on top of the existing Window one? This would allow you to control a view being shown by libraries like DialogHost.Avalonia which would work on browser and desktop. Or you could just only use it for browser, whatever you'd want.

Checking the code, it's not trivial: the viewModels seems coupled to the fact the view is a Window, but I don't think it's too bad: you could have 2 layers of viewModels: one for the window and one for the UserControl.

Idea is to have the basic functionality. While it's something that can be done with js interop (the point of this lib is to not have to define view and viewModel for very simple prompts), being able to use it on both desktop and browser gives the benefit of uniform looks.

So this is just a suggestion. I unfortunately don't have time myself to open a pr for it, but I might as well open this to see if it's something people would be interested.

**Comment by CreateLab** [comment]
fixed in 3.0 version
