### ISSUE TITLE
Trying MessageBox.Avalonia on Raspberry Pi

### ISSUE THREAD

**Issue by PITON369** [AvaloniaCommunity/MessageBox.Avalonia#146]
I'm trying create message box like this:

var messageBoxStandardWindow = MessageBoxManager.GetMessageBoxCustomWindow
                (new MessageBoxCustomParams
                {
                    ContentMessage = "Done.",
                    ContentTitle = "Ок",
                    ButtonDefinitions = new[] { new ButtonDefinition { Name = "Ok" } },
                    Topmost = true,
                }
                ).Show();

In Windows new window creates is topmost, in Raspbian it's creates under main window.

**Comment by CreateLab** [comment]
1) try to update all to 11.0 Avalonia and msbox 3.0

**Comment by PITON369** [comment]
I tryed project MessageBox.Avalonia/Exmaple2.0 and yes it's work, problem is solwed. Thanks!
