### ISSUE TITLE
When I click the cancel button of window' it doesn't work as expected

### ISSUE THREAD

**Issue by berkansasmaz** [AvaloniaCommunity/MessageBox.Avalonia#148]
**Avalonia version:** `11.0.0`
**MessageBox.Avalonia version:** `3.0.0`
**Operating system:** Doesn't matter.

**Note:** This issue was also present in version `3.0.1-rc2`.

---

I have a `MessageBox` as below. If I press the cancel button on the window of this `MessageBox`, `ShowWindowDialogAsync` does not return a value.

```csharp
        var messageBox = MessageBoxManager.GetMessageBoxStandard(
            title,
            text,
            ButtonEnum.YesNo,
            Icon.Question
        );

        return await messageBox.ShowWindowDialogAsync(GetParentWindow()) == ButtonResult.Yes;
```

![Screenshot 2023-07-18 at 10 31 06](https://github.com/AvaloniaCommunity/MessageBox.Avalonia/assets/31216880/52082082-95be-4c7c-8d56-0a9c86e6a103)

The behavior I expect is to return a negative button result, but in the current situation nothing is returned and therefore the flow does not continue, so if we use `ReactiveCommand`, the button remains disabled.

**Comment by CreateLab** [comment]
Check 3.1.0

**Comment by berkansasmaz** [comment]
Problem solved, thanks 🙏
