### ISSUE TITLE
When trying to use `Ctrl+C` to copy text in a MessageBox, a `NotImplementedException` was thrown

### ISSUE THREAD

**Issue by UlyssesWu** [AvaloniaCommunity/MessageBox.Avalonia#150]
OS: Windows 10

![image](https://github.com/AvaloniaCommunity/MessageBox.Avalonia/assets/4312781/5bb74871-e55d-4d15-ab41-af259e59c4c1)

If you select text in a messagebox and press `Ctrl+C`:
![image](https://github.com/AvaloniaCommunity/MessageBox.Avalonia/assets/4312781/415d5876-96ea-4e6f-9d3b-6556c885c52a)

However, the text can still be copied using context menu without error:
![image](https://github.com/AvaloniaCommunity/MessageBox.Avalonia/assets/4312781/c9ec08ec-97e4-41ae-bdb9-6d0dea298275)

**Comment by UlyssesWu** [comment]
https://github.com/AvaloniaCommunity/MessageBox.Avalonia/blob/399539b6f1a82bebc5c1eb1e281f9d9b208e93e1/MsBox.Avalonia/Controls/MsBoxStandardView.axaml#L20-L24

After delete `<KeyBinding Gesture="Ctrl+C" Command="{Binding Copy}" />`, the `Ctrl+C` works as expected. Do we really need this binding?

**Comment by CreateLab** [comment]
Сheck 3.1.0 fix this
