### ISSUE TITLE
Wiki is outdated - "Show()" method no longer exists

### ISSUE THREAD

**Issue by AlexanderBateman8** [AvaloniaCommunity/MessageBox.Avalonia#166]
Helpful examples of the Avalonia MessageBox are given in the Wiki and linked in the readme: https://github.com/AvaloniaCommunity/MessageBox.Avalonia/wiki/Examples

These examples all show creation of the objects and calling them with box.Show(). In the [code](https://github.com/AvaloniaCommunity/MessageBox.Avalonia/blob/master/MsBox.Avalonia/MsBox.cs), the only methods available are:

 - ShowAsync()
 - ShowWindowAsync()
 - ShowWindowDialogAsync()
 - ShowAsPopupAsync()
 
 I've been awaiting ShowAsync() methods for now, and it seems to work fine, but am unsure what the differences are between the Show() method that's used in the wiki and the ShowAsync() method which I use now, or if I can use ShowAsync() without awaiting it. More information on the wiki would be helpful.

**Comment by CreateLab** [comment]
Yes, wiki is outdated sorry, need some more free time to update it
