### ISSUE TITLE
Localize

### ISSUE THREAD

**Issue by kronic** [AvaloniaCommunity/MessageBox.Avalonia#177]
How Localize Yes, No, Abort button content?

**Comment by Agarvaen** [comment]
Hi! You can use styles. Example:

<Style Selector="Button.yes /template/ ContentPresenter#PART_ContentPresenter">
    <Setter Property="Content" Value="MyYes" />
</Style>

<Style Selector="Button.no /template/ ContentPresenter#PART_ContentPresenter">
    <Setter Property="Content" Value="MyNo" />
</Style>
