### ISSUE TITLE
How to use ShowWindowDialogAsync() in MVVM mode

### ISSUE THREAD

**Issue by howzew** [AvaloniaCommunity/MessageBox.Avalonia#180]
For example, the following code:

```
public partial class MainWindowViewModel : ObservableObject
{
    public MainWindowViewModel()
    {
		var box = MessageBoxManager
            .GetMessageBoxStandard("Caption", "Are you sure you would like to delete appender_replace_page_1?",
                ButtonEnum.YesNo);
                
		var result = box.ShowWindowDialogAsync(this);
	}
	
}
```

In mvvm mode, how should "this" be defined here without binding command? I've looked at various examples, and they all seem to use "this", and there are no examples of use in mvvm mode.

**Comment by nwb99** [comment]
I'm stuck in the same situation.

**Comment by CreateLab** [comment]
If u wanna use as dialog u need to solve this problem by urself.
1) pass link to window to vm
2) use call only from view

Or call just showwindow()
