### ISSUE TITLE
MsBox.Avalonia.Enums.Icon.Info should be same as windows standard message box info icon.

### ISSUE THREAD

**Issue by garawaa** [AvaloniaCommunity/MessageBox.Avalonia#187]
![info](https://github.com/user-attachments/assets/a5e581c1-678c-46a6-88d3-a79c7a3caf92)
Or It should allow custom Icon image file. I want to use something standard info ⓘ icon for message. But does not exists. Insteed it shows some search icon

**Comment by CreateLab** [comment]
it's allow custom image file

**Comment by garawaa** [comment]
How to use costom image file? I did not find in documentation. And It also does not show modally in wasm platform.

**Comment by Upanc** [comment]
> How to use costom image file? I did not find in documentation. And It also does not show modally in web platform.

messageboxcustomparams imageicon
