### ISSUE TITLE
Set applications icon in message box title bar panel

### ISSUE THREAD

**Issue by epicdoomchenko** [AvaloniaCommunity/MessageBox.Avalonia#190]
In the current implementation, neither the Standard set of parameters nor the Custom set provides an opportunity to set a custom icon in the title bar of the message box, for example:
![изображение](https://github.com/user-attachments/assets/b07c0e84-fc49-4e5e-97f5-886b5267ce8c)

**Comment by Luk164** [comment]
Why is this closed? I have the same issue so it is not solved yet

**Comment by epicdoomchenko** [comment]
@Luk164  Just set path to your icon into field WindowIcon witch is defined in AbstractMessageBoxParams (parent class for MessageBoxStandardParams and MessageBoxCustomParams)
I solve my problem like this:
```
var myParamsnew MessageBoxCustomParams
{
    WindowIcon = new WindowIcon("path/to/my/icon.png"),
    /* other definitions here */
}
```

**Comment by Luk164** [comment]
> @Luk164  Just set path to your icon into field WindowIcon witch is defined in AbstractMessageBoxParams (parent class for MessageBoxStandardParams and MessageBoxCustomParams)
> I solve my problem like this:
> ```
> var myParams = new MessageBoxCustomParams
> {
>     WindowIcon = new WindowIcon("path/to/my/icon.png"),
>     /* other definitions here */
> }
> ```

Right, but in that case, shouldn't the default for non-custom class be to use the same icon on both instead?

**Comment by epicdoomchenko** [comment]
@Luk164 just use somethng like this:
```
new MessageBoxStandardParams
{
    WindowIcon = new WindowIcon(),
    /* other definitions here */
}
```
