### ISSUE TITLE
The ability to set the focus on the button.

### ISSUE THREAD

**Issue by rignatev** [AvaloniaCommunity/MessageBox.Avalonia#44]
Hi!

Can you add the ability to choose default action button in paramters?

For example, MessageBoxStandardParams with ButtonDefinitions = ButtonEnum.YesNo - sets button "Yes" by default.
I want to choose wich button will be default action.

**Comment by mysteryx93** [comment]
+1

Before implementing advanced features, first need parity with standard MessageBox features.
