### ISSUE TITLE
Right click context menu to copy text is disabled

### ISSUE THREAD

**Issue by sn4k3** [AvaloniaCommunity/MessageBox.Avalonia#64]
![image](https://user-images.githubusercontent.com/113281/116797512-7c4fd380-aade-11eb-9cab-9251a580cbb3.png)

**Comment by CreateLab** [comment]
@sn4k3 u may use cntrl+c as dafault way.
About menus at this moment has no ideas, but check

**Comment by sn4k3** [comment]
To say the truth the Ctrl + C never worked with me in one of the versions of message box. I always had to do right click + Copy to do the copying of the selected text, my app users wasn't unable to use ctrl +c as well

**Comment by sn4k3** [comment]
Ok i found some problems... There's also much confusion on the code, redundancy

![image](https://user-images.githubusercontent.com/113281/118300585-02561c00-b4da-11eb-9815-a1ebc0a2f78f.png)

![image](https://user-images.githubusercontent.com/113281/118300736-2d407000-b4da-11eb-96de-d5bd964f6c88.png)

![image](https://user-images.githubusercontent.com/113281/118300777-392c3200-b4da-11eb-94ff-63fe84965366.png)


On 3 different files, many properties are repeated. Ctrl + C doesnt work because property is always empty since you are getting the wrong one (due that redundancy lead to errors)

**Comment by sn4k3** [comment]
I'm getting near to a fix :)

![image](https://user-images.githubusercontent.com/113281/118309012-92995e80-b4e4-11eb-8d26-99205830a199.png)

**Comment by sn4k3** [comment]
The context menu disallow copy is avalonia bug, i will open a bug report with them

**Comment by CreateLab** [comment]
@sn4k3 
https://github.com/AvaloniaUI/Avalonia/pull/5935
just wait

**Comment by CreateLab** [comment]
about cntrl + c 
check
