### ISSUE TITLE
"Eye" color

### ISSUE THREAD

**Issue by CreateLab** [AvaloniaCommunity/MessageBox.Avalonia#68]
Set eye color depends of window style. (Now allaways orange)
![изображение](https://user-images.githubusercontent.com/33497292/118927761-ef64a100-b94a-11eb-91d4-fb73ad4442df.png)
![изображение](https://user-images.githubusercontent.com/33497292/118927835-0c00d900-b94b-11eb-9564-4b2556d01fa1.png)
![изображение](https://user-images.githubusercontent.com/33497292/118927917-289d1100-b94b-11eb-870b-914a5810a057.png)

**Comment by Fruchtzwerg94** [comment]
See my PR #92
