### ISSUE TITLE
Self defined button with custom font, the caption keep left aligned.

### ISSUE THREAD

**Issue by esonhon** [AvaloniaCommunity/MessageBox.Avalonia#73]
The real code:
`MessageBox.Avalonia.MessageBoxManager
                .GetMessageBoxCustomWindow(new MessageBoxCustomParams
                {
                    ContentTitle = title,
                    ContentMessage = message,
                    FontFamily = "Microsoft YaHei,Simsun",
                    Icon = Icon.Error,
                    WindowIcon = null,
                    ButtonDefinitions = new[] {
                        new ButtonDefinition {Name = "确定", Type = ButtonType.Colored},
                    },
`                   WindowStartupLocation = WindowStartupLocation.CenterOwner,
                    Style = Style.Windows
                });`

Button caption "确定" if left aligned, I think center aligned should be OK.

**Comment by CreateLab** [comment]
![изображение](https://user-images.githubusercontent.com/33497292/136687546-f8b666b0-bf40-4afb-80f3-a9f794e7632c.png)
