### ISSUE TITLE
Change Window icon in top-left corner

### ISSUE THREAD

**Issue by lissity** [AvaloniaCommunity/MessageBox.Avalonia#75]
Is there support for changing the Window icon in the top-left corner?

**Comment by CreateLab** [comment]
![изображение](https://user-images.githubusercontent.com/33497292/129877814-e361a9bd-0e9c-4650-adf6-87f65832f704.png)
![изображение](https://user-images.githubusercontent.com/33497292/129877871-714b639a-929a-4343-a385-69a4bec88a30.png)

**Comment by lissity** [comment]
Thank you for the help!
Yes, the issue can be closed.
