### ISSUE TITLE
GetMessageBoxStandardWindow error on Debian

### ISSUE THREAD

**Issue by Vladimir-Str** [AvaloniaCommunity/MessageBox.Avalonia#76]
I tried to call a dialog with various parameters, with an icon, without an icon, and others, but I always get an error
My current code:
```
                var exMessageBox = MessageBox.Avalonia.MessageBoxManager.GetMessageBoxStandardWindow(new MessageBox.Avalonia.DTO.MessageBoxStandardParams
                {
                    ButtonDefinitions = ButtonEnum.Ok,
                    ContentTitle = "Error",
                    ContentMessage = ex.Message,
                    //Icon = Icon.Error,
                    Style = Style.MintLinux
                });
                exMessageBox.Show();
```
Error
[Binding] Error in binding to 'Avalonia.Controls.Image'.'IsVisible': 'Could not find a matching property accessor for 'Icon' on 'MessageBox.Avalonia.ViewModels.MsBoxStandardViewModel'' (Image #22478116)

**Comment by Vladimir-Str** [comment]
But it's work ok on Windows

**Comment by CreateLab** [comment]
@Vladimir-Str as hot fix, u may use new imagebox 
```cs
 var messageBoxCustomWindow = MessageBox.Avalonia.MessageBoxManager
                .GetMessageBoxCustomWindow(new MessageBoxCustomParamsWithImage
                {
                    Style = Style.UbuntuLinux,
                    ContentMessage = "Message",
                    Icon = new Bitmap("./icon-rider.png"), // give icon
                    ButtonDefinitions = new[] {
                        new ButtonDefinition {Name = "My"},
                        new ButtonDefinition {Name = "Buttons", Type = ButtonType.Colored}
                    },
                    WindowStartupLocation = WindowStartupLocation.CenterOwner
                });
 messageBoxCustomWindow.Show();
 ```
 i try to check ur bug

**Comment by Vladimir-Str** [comment]
Thank you very much!

**Comment by Vladimir-Str** [comment]
I also tried HyperlinkDialog but:
[Binding] Error in binding to 'Avalonia.Controls.Image'.'IsVisible': 'Could not find a matching property accessor for 'Icon' on 'MessageBox.Avalonia.ViewModels.MsBoxHyperlinkViewModel'' (Image #22478116)

**Comment by Vladimir-Str** [comment]
> @Vladimir-Str as a hot fix, u may use new imagebox
> 
> ```cs
>  var messageBoxCustomWindow = MessageBox.Avalonia.MessageBoxManager
>                 .GetMessageBoxCustomWindow(new MessageBoxCustomParamsWithImage
>                 {
>                     Style = Style.UbuntuLinux,
>                     ContentMessage = "Message",
>                     Icon = new Bitmap("./icon-rider.png"), // give icon
>                     ButtonDefinitions = new[] {
>                         new ButtonDefinition {Name = "My"},
>                         new ButtonDefinition {Name = "Buttons", Type = ButtonType.Colored}
>                     },
>                     WindowStartupLocation = WindowStartupLocation.CenterOwner
>                 });
>  messageBoxCustomWindow.Show();
> ```
> 
> i try to check ur bug

[Binding] Error in binding to 'Avalonia.Controls.Image'.'IsVisible': 'Could not find a matching property accessor for 'Icon' on 'MessageBox.Avalonia.ViewModels.MsBoxCustomViewModel'' (Image #32894845)

**Comment by CreateLab** [comment]
Looks like platform depends bug in AvaloniaUI. If u may create mvp and send bugreport to Avalonia, it'll be cool. Or I try to do this next weekend.

**Comment by CreateLab** [comment]
Here u may find rus support https://t.me/AvaloniaRU

**Comment by Vladimir-Str** [comment]
> Looks like platform depends bug in AvaloniaUI. If u may create mvp and send bugreport to Avalonia, it'll be cool. Or I try to do this next weekend.

ok, i send.

**Comment by Vladimir-Str** [comment]
Ooh, this error was caused by I use .Shutdown(); without awaiting exMessageBox.Show() like in WPF
