### ISSUE TITLE
Cannot display simplified Chinese

### ISSUE THREAD

**Issue by yangjieshao** [AvaloniaCommunity/MessageBox.Avalonia#77]
![image](https://user-images.githubusercontent.com/3275834/130314912-1ca951cc-aaa7-482e-a60e-7f50000bd2d7.png)

![image](https://user-images.githubusercontent.com/3275834/130314915-293d4544-7ea7-4210-8d28-87dd36f6e6fe.png)

**Comment by CreateLab** [comment]
https://github.com/AvaloniaCommunity/MessageBox.Avalonia/pull/50/commits/d75a12fcb9fcca5ed547706bdf8a023d6f31e986
It's Avalonia problem. Way to fix.
Or set default font for all app
