### ISSUE TITLE
Text not fully visible using no icon

### ISSUE THREAD

**Issue by Fruchtzwerg94** [AvaloniaCommunity/MessageBox.Avalonia#84]
Setting no icon to the message box:

`Icon = Icon.None;`

leads to not fully visible / overlapped text:

![grafik](https://user-images.githubusercontent.com/29866610/144261532-3302c098-d938-402a-9091-2f7df923d6d6.png)

With icon, the whole text is visible:
![grafik](https://user-images.githubusercontent.com/29866610/144261430-f610e693-cfab-4dcb-b275-8fe0baaef949.png)

This behaviour is observed at least on Windows and Linux (Raspbian).

**Comment by CreateLab** [comment]
Try to fix size of window
or add empty space in text.
That's avalonia ui problem

**Comment by Fruchtzwerg94** [comment]
Yes, unfortunately, I can confirm this issue is caused by Avalonia itself. Do you see another way to solve this issue ... I don't like the way to set a fixed sice or some empty space in text.

**Comment by CreateLab** [comment]
Create fix size of window with constants height and weight

**Comment by Fruchtzwerg94** [comment]
Yes sure, that would work - but I don't like it to set hard values for the size here. But I think currently there is no other option.

**Comment by mysteryx93** [comment]
I've seen the same problem. Adding Environment.NewLine to the context fixed it.

**Comment by CreateLab** [comment]
![изображение](https://user-images.githubusercontent.com/33497292/153755941-9d36a150-e34b-42a7-9f73-f4d2b81f60d7.png)
![изображение](https://user-images.githubusercontent.com/33497292/153755969-02d7088d-62eb-40ba-a05a-c6be2c151fd1.png)

**Comment by CreateLab** [comment]
fixed in new version

**Comment by Fruchtzwerg94** [comment]
Cant confirm that this is fixed. Your sample contains more buttons where it works. But the original issue is still there.

**Comment by jamsoft** [comment]
I've just run into this on the latest 2.0.1 release

Will investigate the solutions mentioned above.

<img width="262" alt="mesbox" src="https://user-images.githubusercontent.com/2502211/173902440-70bf83a7-9f76-4c7e-87e0-d0ce1028e1ac.PNG">

**Comment by CreateLab** [comment]
bad( try to fix

**Comment by CreateLab** [comment]
> I also have this problem even with latest version

https://github.com/AvaloniaCommunity/MessageBox.Avalonia/issues/84#issuecomment-1157451427
this is hot fix. I try to correct fix this

**Comment by anovik** [comment]
Thanks, hot fix is also working for me. Waiting for the fix/update.

**Comment by CreateLab** [comment]
![изображение](https://user-images.githubusercontent.com/33497292/176845481-8710b917-8d72-4816-bc92-63e4927142dc.png)
@jamsoft 
@anovik 
In my test all is ok, may u share demo, when all is destroyed

**Comment by anovik** [comment]
With 2.0.1 version I can reproduce on Windows the problem with a standard call:

```
var messageBoxStandardWindow = MessageBox.Avalonia.MessageBoxManager
                .GetMessageBoxStandardWindow("Caption", "Some text and its end is not visible here", ButtonEnum.YesNo, Icon.None);
```

**Comment by CreateLab** [comment]
@anovik 
![изображение](https://user-images.githubusercontent.com/33497292/176859230-1fda2e18-dd60-45ce-a254-21673929228a.png)

May u come to ur community in telegram 
( en - https://t.me/Avalonia )
( ru  - https://t.me/AvaloniaRU)

**Comment by anovik** [comment]
@CreateLab OK, try with text "Are you sure you would like to delete appender_replace_page_1?"

![изображение](https://user-images.githubusercontent.com/8667411/176869268-6390591c-3161-44f5-8b13-f6215e880f1a.png)
"

(I can scroll and see the rest on the second line)

For some texts with comparable length it is really working, but for some not, is it a problem with wrapping? In my example too long word breaks the messagebox.

**Comment by CreateLab** [comment]
Check 2.0.2 version

**Comment by anovik** [comment]
@CreateLab Thanks, I've updated to 2.0.2 and it is bette now, but there is still a problem, see screenshot:

![bug](https://user-images.githubusercontent.com/8667411/179449959-fa4026c3-9974-4814-a70a-795f68b0965b.png)

If I append Environment.NewLine hot fix, it looks fine. ("?" is on the same line).
