### ISSUE TITLE
Button Functions

### ISSUE THREAD

**Issue by ZenKit0** [AvaloniaCommunity/MessageBox.Avalonia#86]
Hello!
I'm writing notepad in Avalonia Framework and I want to add "Save before exit" Dialog. How can I assign function to button to save file?

**Comment by CreateLab** [comment]
```cs
public async Task OnClose()
{
var msBox = MessageBox.Avalonia.MessageBoxManager.GetMessageBoxStandardWindow(new MessageBoxStandardParams
            {
                ContentMessage = "Wonna out without save?",
                ButtonDefinitions = ButtonEnum.YesNo
            });
            var buttonResult = await msBox.Show();
            if (buttonResult == ButtonResult.Yes)
            {
                Exit();
            }

            Save();
            Exit();
}
```
Exit and Save - your own methods

**Comment by ZenKit0** [comment]
> ```cs
> public async Task OnClose()
> {
> var msBox = MessageBox.Avalonia.MessageBoxManager.GetMessageBoxStandardWindow(new MessageBoxStandardParams
>             {
>                 ContentMessage = "Wonna out without save?",
>                 ButtonDefinitions = ButtonEnum.YesNo
>             });
>             var buttonResult = await msBox.Show();
>             if (buttonResult == ButtonResult.Yes)
>             {
>                 Exit();
>             }
> 
>             Save();
>             Exit();
> }
> ```
> 
> Exit and Save - your own methods

How can I trigger it in MainWindowVievModel at closing program? When I click X and text are not null -> open this dialog.

**Comment by CreateLab** [comment]
you should throw info about closing from window to view model
https://stackoverflow.com/questions/3683450/handling-the-window-closing-event-with-wpf-mvvm-light-toolkit
