### ISSUE TITLE
Linux issues

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaCommunity/MessageBox.Avalonia#88]
After trying it on Linux, there are a few more issues.

The MessageBox doesn't show up centered to the parent. That's an issue with Avalonia; but as for right-now, [here's the fix](https://github.com/mysteryx93/NaturalGroundingPlayer/blob/master/Common.Avalonia/Controls/CommonWindow.cs).

We can close the dialog with Esc or Enter; but not Space. We have to do Tab,Tab,Space to close it. Should set the initial focus to the default button.

Min/Max buttons are displayed. Not being able to hide them is a Avalonia problem. On Linux, pressing Min flickers then does nothing. Pressing Max hides the window border/title and centers the window. Just some weird behavior.

**Comment by Fruchtzwerg94** [comment]
I think centering correctly should be handled by Avalonia itself. Do you know if there is already an issue related to that there?

**Comment by mysteryx93** [comment]
There are discussions about it, but no release date for a fix. Some stuff will wait until Wayland renderer release before getting fixed.
