### ISSUE TITLE
ShowDialog() without owner

### ISSUE THREAD

**Issue by TopBaJLbD** [AvaloniaCommunity/MessageBox.Avalonia#97]
Is it possible to use this library for any lifetime type of the application or it should be used only for desktop?
I think, in case of using [IClassicDesktopStyleApplicationLifetime](https://github.com/AvaloniaUI/Avalonia/blob/2c7ae3a50fdbf7878f8dadc72fc5ddf5b24cd546/src/Avalonia.Controls/ApplicationLifetimes/IClassicDesktopStyleApplicationLifetime.cs) we can use `Windows` property to get an active window and use it as a dialog owner.

**Comment by mysteryx93** [comment]
If there is no owner available, it could call Show instead of ShowDialog.

This could allow displaying a message before the application is started or after it is closed.

**Comment by TopBaJLbD** [comment]
So, my idea was to create a default implementation without the owner. In this case, we can use a currently active window as an owner. Is it a good practice to do it with other application lifetimes?

**Comment by SKProCH** [comment]
I think what other application lifetimes doesn't allow to show dialogs via windows at all. Any environment with SingleView (such as mobiles and WASM) doesn't allow to create additional windows and msbox doesn't work there.
