### ISSUE TITLE
Base window configuration

### ISSUE THREAD

**Issue by TopBaJLbD** [AvaloniaCommunity/MessageBox.Avalonia#98]
We have minimize and maximize buttons in the base window. I think it would be better to hide them by default and also provide a possibility to configure it.

**Comment by CreateLab** [comment]
I wanna save system decorations. And in some linux like KDE have troubles with hide buttons and save sys decorations. Any ideas?

**Comment by TopBaJLbD** [comment]
I see. I checked existing issues of the Avalonia project and I think we need to wait an update with [issue](https://github.com/AvaloniaUI/Avalonia/issues/3422) fix.
